name: uat test terraform
on:
  pull_request:
    branches: [uat, main]
    types: [opened, synchronize]

jobs:
  uat-test-terraform:
    runs-on: wuat-ec2
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: List directory
        run: |
          ls -ltr ${{ github.workspace }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-southeast-2

      - name: Plan infrastructure
        run: |
          cd cloud
          tfswitch
          terraform init
          terraform validate
          terraform fmt --recursive
          terraform workspace select uat
          terraform plan \
            -var-file vars/uat/common.tfvars

      - run: echo "🍏 This job's status is ${{ job.status }}."
