name: uat deploy terraform
on:
  push:
    paths:
      - '!**'
      - 'cloud/**'
      - 'app/**'
      - 'lambda-layers/**'
    branches:
      - uat
jobs:
  uat-terraform:
    runs-on: wuat-ec2
    steps:

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: uat

      - name: List directory
        run: |
          ls -ltr ${{ github.workspace }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ap-southeast-2

      - name: Deploy lambda layer
        run: |
          cd ${{ github.workspace }}/lambda-layers
          source /root/.bash_profile
          serverless plugin install -n serverless-python-requirements
          serverless deploy --verbose --stage uat

      - name: Apply infrastructure
        run: |
          cd ${{ github.workspace }}/cloud
          tfswitch
          terraform init
          terraform workspace select uat
          terraform apply \
            -var-file vars/uat/common.tfvars \
            -auto-approve

      - run: echo "🍏 This job's status is ${{ job.status }}."
